# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\"3\n\x0e\x41nalysisResult\x12\x0f\n\x07tuit_id\x18\x01 \x01(\t\x12\x10\n\x08\x61nalysis\x18\x02 \x01(\t\"B\n\x16RecommendationResponse\x12\x0f\n\x07tuit_id\x18\x01 \x01(\t\x12\x17\n\x0frecommendations\x18\x02 \x03(\t2w\n\x15RecommendationService\x12^\n\x12GetRecommendations\x12\x1f.recommendations.AnalysisResult\x1a\'.recommendations.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISRESULT']._serialized_start=42
  _globals['_ANALYSISRESULT']._serialized_end=93
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=95
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=161
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=163
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
